# Generated by Django 3.2.3 on 2021-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('releaseInfo', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
            ],
        ),
    ]
